<a href="https://colab.research.google.com/github/paulgureghian/TensorFlow_Projects/blob/master/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Created by Paul A. Gureghian in Jan 2019.**

**I will create a TensorFlow Tensor full of ones using the 'TensorFlow Ones' operation.**

In [0]:
### Import TensorFlow
import tensorflow as tf

In [2]:
### Print TensorFlow version 
print(tf.__version__) 

1.12.0


In [0]:
### Create a TF Tensor of integers
tf_int_ones_ex = tf.ones(shape =[1,2,3], dtype ='int32') 

In [4]:
### Print the int Tensor
print(tf_int_ones_ex) 

Tensor("ones:0", shape=(1, 2, 3), dtype=int32)


In [0]:
### Create a TF tensor of floats 
tf_float_ones_ex = tf.ones(shape =[2,3,4], dtype ='float32')

In [6]:
### Print the float Tensor 
print(tf_float_ones_ex)

Tensor("ones_1:0", shape=(2, 3, 4), dtype=float32)


In [0]:
### Launch the computational graph session
sess = tf.Session() 

In [0]:
### Initialize the global variables in the graph
sess.run(tf.global_variables_initializer()) 


In [9]:
### Print the int Tensor 
print(sess.run(tf_int_ones_ex)) 

[[[1 1 1]
  [1 1 1]]]


In [10]:
### Print the float Tensor
print(sess.run(tf_float_ones_ex)) 

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [0]:
### Close the TF session
sess.close() 